version: "3.8"

services:
  business-web:
    image: pictureme-business:latest
    container_name: pictureme-business-web
    ports:
      - "8081:8080"
    environment:
      VITE_API_URL: "https://go.pictureme.now"
      VITE_AUTH_URL: "https://go.pictureme.now"
      VITE_BASE_URL: "https://business.pictureme.now"
      VITE_MINIO_ENDPOINT: "s3.amazonaws.com"
      VITE_MINIO_BUCKET: "pictureme.now"
      VITE_MINIO_SERVER_URL: "https://s3.amazonaws.com"
      VITE_STRIPE_PUBLISHABLE_KEY: "${VITE_STRIPE_PUBLISHABLE_KEY}"
    restart: unless-stopped
